spring.application.name: website

server:
  port: 8080
  
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1212
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
  sql:
    init:
      mode: never
      
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
    

remember:
  me:
    key: ${REMEMBER_ME_KEY:topSecret}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE
    
    
image:
  upload:
    formNewTreatmentDir: "C:\\Users\\MihailBozov\\IdeaProjects\\website\\src\\main\\resources\\static\\images\\treatments"
    
    
#image:
#  upload:
#    dir: "C:\\Users\\MihailBozov\\IdeaProjects\\website\\src\\main\\resources\\static\\images"
#    
    
#formNewTreatment:
#  upload:
#    dir: "C:\\Users\\MihailBozov\\IdeaProjects\\website\\src\\main\\resources\\static\\images\\treatments"

    