
server:
  port: 8081

spring:
  application:
    name: dental-care-treatments
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dental-treatment?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1212
  
  jpa:
    open-in-view: on
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never
  
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
    
    
    #image:
    #  upload:
    #    formNewTreatmentDir: "C:\\Users\\MihailBozov\\IdeaProjects\\Dental-Care\\website\\src\\main\\resources\\static\\images\\treatments"
    
    
    #image:
    #  upload:
    #    dir: "C:\\Users\\MihailBozov\\IdeaProjects\\website\\src\\main\\resources\\static\\images"
    #    
    
    #formNewTreatment:
    #  upload:
    #    dir: "C:\\Users\\MihailBozov\\IdeaProjects\\website\\src\\main\\resources\\static\\images\\treatments"

    